# Generated by Django 5.2.7 on 2025-10-20 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tipoVeiculo',
            fields=[
                ('idVeiculo', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('tipo_Veiculo', models.CharField(max_length=50)),
                ('numero_Veiculo', models.DateField()),
                ('placa_Veiculo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'app_veiculo',
                'verbose_name_plural': 'app_veiculos',
                'db_table': 'tabela_veiculo',
            },
        ),
        migrations.CreateModel(
            name='rota_Veiculo',
            fields=[
                ('idClassificacao', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('rotas', models.CharField(max_length=100)),
                ('semana', models.CharField(max_length=100)),
                ('placa_Veiculo_classificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotas', to='app_veiculo.tipoveiculo')),
            ],
            options={
                'verbose_name': 'app_veiculo',
                'verbose_name_plural': 'app_veiculos',
                'db_table': 'tabela_veiculo_rotas',
            },
        ),
    ]
