# Generated by Django 5.2.7 on 2025-10-25 13:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_veiculo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(help_text='Formato: ABC1234 ou ABC1D23', max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de placa inválido. Use o formato ABC1234 ou ABC1D23', regex='^[A-Z]{3}[0-9]{4}$|^[A-Z]{3}[0-9][A-Z][0-9]{2}$')])),
                ('tipo', models.CharField(choices=[('compactador', 'Compactador'), ('caçamba', 'Caçamba')], help_text='Selecione o tipo do veículo', max_length=20)),
                ('numero_caminhao', models.CharField(help_text='Número identificador do caminhão', max_length=20, unique=True)),
                ('ativo', models.BooleanField(default=True, help_text='Veículo ativo no sistema')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'db_table': 'veiculos',
                'ordering': ['placa'],
            },
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(help_text='Local da coleta', max_length=200)),
                ('data', models.DateField(help_text='Data da coleta')),
                ('horario', models.TimeField(help_text='Horário da coleta')),
                ('observacoes', models.TextField(blank=True, help_text='Observações adicionais', null=True)),
                ('concluida', models.BooleanField(default=False, help_text='Rota concluída')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('veiculo', models.ForeignKey(help_text='Veículo responsável pela rota', on_delete=django.db.models.deletion.CASCADE, related_name='rotas', to='app_veiculo.veiculo')),
            ],
            options={
                'verbose_name': 'Rota',
                'verbose_name_plural': 'Rotas',
                'db_table': 'rotas',
                'ordering': ['-data', 'horario'],
                'unique_together': {('veiculo', 'data', 'horario')},
            },
        ),
        migrations.DeleteModel(
            name='rota_Veiculo',
        ),
        migrations.DeleteModel(
            name='tipoVeiculo',
        ),
    ]
