# Generated by Django 5.2.7 on 2025-10-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_veiculo', '0002_veiculo_rota_delete_rota_veiculo_delete_tipoveiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rota',
            name='dias_semana',
            field=models.CharField(blank=True, help_text='Dias da semana (ex: Seg, Ter, Qua)', max_length=50, null=True),
        ),
    ]
