# Generated by Django 5.2.7 on 2025-10-25 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_veiculo', '0003_rota_dias_semana'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rota',
            options={'ordering': ['horario'], 'verbose_name': 'Rota', 'verbose_name_plural': 'Rotas'},
        ),
        migrations.AlterUniqueTogether(
            name='rota',
            unique_together={('veiculo', 'horario')},
        ),
        migrations.RemoveField(
            model_name='rota',
            name='data',
        ),
    ]
