# Generated by Django 5.2.7 on 2025-10-25 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_veiculo', '0004_alter_rota_options_alter_rota_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemaColeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_problema', models.CharField(choices=[('coleta_nao_feita', 'Coleta sem ser feita'), ('area_dificil_acesso', 'Áreas de difícil acesso'), ('problema_mecanico', 'Problema mecânico'), ('outros', 'Outros')], help_text='Tipo do problema identificado', max_length=30)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', help_text='Prioridade do problema', max_length=10)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_andamento', 'Em Andamento'), ('resolvido', 'Resolvido'), ('cancelado', 'Cancelado')], default='aberto', help_text='Status atual do problema', max_length=15)),
                ('descricao', models.TextField(help_text='Descrição detalhada do problema')),
                ('local_problema', models.CharField(help_text='Local onde ocorreu o problema', max_length=200)),
                ('data_ocorrencia', models.DateTimeField(help_text='Data e hora da ocorrência do problema')),
                ('responsavel_relato', models.CharField(help_text='Nome do responsável que relatou o problema', max_length=100)),
                ('solucao', models.TextField(blank=True, help_text='Solução aplicada (preenchido quando resolvido)', null=True)),
                ('data_resolucao', models.DateTimeField(blank=True, help_text='Data e hora da resolução do problema', null=True)),
                ('observacoes', models.TextField(blank=True, help_text='Observações adicionais', null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('rota', models.ForeignKey(blank=True, help_text='Rota relacionada ao problema (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problemas', to='app_veiculo.rota')),
                ('veiculo', models.ForeignKey(help_text='Veículo relacionado ao problema', on_delete=django.db.models.deletion.CASCADE, related_name='problemas', to='app_veiculo.veiculo')),
            ],
            options={
                'verbose_name': 'Problema de Coleta',
                'verbose_name_plural': 'Problemas de Coleta',
                'db_table': 'problemas_coleta',
                'ordering': ['-data_ocorrencia', '-prioridade'],
            },
        ),
    ]
